title: Wir sind Weingarten
description: Gemeinsam sind wir Stark
theme: jekyll-theme-minimal # Ein Standard-Theme als Basis, falls nötig
baseurl: "" # Wichtig für deine Custom Domain
url: "https://wirsindweingarten.de"

# Markdown Einstellungen
markdown: kramdown
plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/news/page:num/"